# Generated by Django 5.2.1 on 2025-10-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_compra_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
